language: cpp

dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - qemu-user-static

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

branches:
  only:
    - master
    - develop
    - hotfix/ci-builds
    - /^v\d+\.\d+\.\d+(-S*)?$/

jobs:
  include:
    ## amd64
    - stage: build images
      name: amd64
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u driplineorg -r dripline-python -t v3.10.1 -a amd64 -i project8/dragonfly:`echo ${TRAVIS_BRANCH} | tr / _`
    ## arm
    - stage: build images
      name: arm32v7
      before_install: .travis/setup_emulation.sh
      script:
        - set -e
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u driplineorg -r dripline-python -t v3.10.1-arm -a arm7 -i project8/dragonfly:`echo ${TRAVIS_BRANCH} | tr / _`
    - stage: assemble manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n project8/dragonfly:`echo ${TRAVIS_BRANCH} | tr / _`
