name: psyllid_service
module: Spimescape
broker: higgsino.physics.ucsb.edu
endpoints:
  - name: psyllid_interface
    module: PsyllidAcquisitionInterface
    # debug only options
    debug_mode_without_database: False
    
    command_terminator: "\n"
    response_terminator: "\n"
    # daq_run_interface params
    #metadata_target: metadata_ignatius
    #metadata_gets:
    # ROACH2 DAQ Interface params
    daq_queue : 'psyllid'
    psyllid_preset : 'str-1ch'
    udp_receiver_port : 4002
    daq_name: 'Psyllid'
    path_to_egg_file_location : "some_path"
    lf_lo_endpoint_name: waffles
    run_table_endpoint: run_table
    #max_nb_files: 100
    #filename_prefix: 'rid'
    #directory_path: "H:\\"
    meta_data_directory_path: "/data/hot"
