name: psyllid_service
module: Spimescape
broker: higgsino.physics.ucsb.edu
endpoints:
  - name: psyllid_interface
    module: PsyllidAcquisitionInterface

    # debug only options
    debug_mode_without_database: True
    debug_mode_without_metadata_broadcast: True
    
    command_terminator: "\n"
    response_terminator: "\n"

    # daq_run_interface params
    run_table_endpoint: run_table
    filename_prefix: 'rid'
    directory_path: "/home/cclaesse"
    #meta_data_directory_path: "/data/hot"
    #metadata_target: "/home/cclaesse/test_files/"
    #metadata_gets:
    
    daq_queue : 'psyllid'
    daq_name: 'Psyllid'
    psyllid_preset : 'str-1ch'
    udp_receiver_port : 4002
    
    egg_file_location : "/home/cclaesse/test_files/"
    lf_lo_endpoint_name: waffles
    log_interval: 0.1
    #max_nb_files: 100
    
setup_calls:
  - target: psyllid_interface
    method: _finish_configure
