name: psyllid_service
module: Spimescape
broker: higgsino.physics.ucsb.edu
endpoints:
  - name: psyllid_interface
    module: PsyllidAcquisitionInterface

    # debug only options
    debug_mode_without_database: True
    debug_mode_without_metadata_broadcast: True
    
    command_terminator: "\n"
    response_terminator: "\n"

    # daq_run_interface params
    run_table_endpoint: run_table
    filename_prefix: 'psyllid'
    directory_path: "/home/cclaesse/psyllid_test_data"
    metadata_directory_path: "/home/cclaesse/psyllid_test_data"

    metadata_state_target: run_metadata
    
    daq_queue : 'psyllid'
    daq_name: 'Psyllid'
    psyllid_preset : 'str-1ch'
    udp_receiver_port : 23530
    
    
    #lf_lo_endpoint_name: lf_lo_lower_cw_freq
    log_interval: 1
    max_nb_files: 10
#setup_calls:
#  - target: psyllid_interface
#    method: _finish_configure
