name: roach2_service
module: Spimescape
broker: higgsino.physics.ucsb.edu
endpoints:
  - name: roach2_interface
    module: Roach2Interface

    # debug only options
    debug_mode_without_database: True
    debug_mode_without_metadata_broadcast: True
    
    command_terminator: "\n"
    response_terminator: "\n"


    # ethernet SCPI params
    #socket_info: ("led.p8", communication_port)
    command_terminator: "\n"
    response_terminator: "\n"

    # daq_run_interface params
    daq_queue : 'roach2'
    daq_name: 'ROACH2'
    roach2_hostname: led.p8

    
    metadata_state_target: run_metadata
    run_table_endpoint: run_table
    
