name: roach2_service
module: Spimescape
broker: higgsino.physics.ucsb.edu
endpoints:
  - name: roach2_interface
    module: Roach2Interface

    # debug only options
    debug_mode_without_database: True
    debug_mode_without_metadata_broadcast: True
    
    command_terminator: "\n"
    response_terminator: "\n"


    # ethernet SCPI params
    #socket_info: ("led.p8", communication_port)
    command_terminator: "\n"
    response_terminator: "\n"

    # daq_run_interface params
    daq_queue : 'roach2'
    daq_name: 'ROACH2'
    roach2_hostname: led.p8
    dest_port: 10.0.11.1
    dest_port: 23530
    dest_mac: e4:1d:2d:14:96:e0
    source_ip: 10.0.11.2
    source_port: 4000
    source_mac: 02:02:10:00:11:02

    
    metadata_state_target: run_metadata
    run_table_endpoint: run_table
    
