name: roach2_service
module: Spimescape
broker: myrna.p8
endpoints:
  - name: roach2_interface
    module: Roach2AcquisitionInterface
    # debug only options
    debug_mode_without_database: False
    # ethernet SCPI params
    socket_info: ("roach2.p8", communication_port)
    command_terminator: "\n"
    response_terminator: "\n"
    # daq_run_interface params
    metadata_target: metadata_ignatius
    #metadata_gets:
    # ROACH2 DAQ Interface params
    daq_queue = 'psyllid'
    psyllid_preset = 'str-1ch'
    udp_receiver_port = 4001
    daq_name: 'ROACH2'
    #roach2_hostname = 'led'
    lf_lo_endpoint_name: waffles
    run_table_endpoint: run_table
    max_nb_files: 10000
    filename_prefix: 'rid'
    directory_path: "H:\\"
    meta_data_directory_path: "/data/hot"
